---

- name: Satellite | Capsule Install | Prerequisites | Registery with Satellite Server
  include_role:
    name: satellite_register

- name: Satellite | Capsule Install | Prerequisites | Include tasks for Enabling Repositories
  include_tasks: tasks/repositories.yml
  vars:
    repositories:
      - rhel-7-server-rpms
      - rhel-7-server-satellite-capsule-6.3-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-satellite-tools-6.3-rpms

- name: Satellite | Capsule Install | Prerequisites | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - chrony
    - firewalld
    - 'satellite-capsule'

- name: Satellite | Capsule Install | Prerequisites | Enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - chronyd
    - firewalld

- name: Satellite | Capsule Install | Prerequisites | Configure Firewall Ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items: "{{ satellite_firewall_ports }}"
